package com.typ.nabda.core.model

enum class GestureType {
    // 1 Finger
    ONE_FINGER_SWIPE_UP,
    ONE_FINGER_SWIPE_DOWN,
    ONE_FINGER_SWIPE_LEFT,
    ONE_FINGER_SWIPE_RIGHT,
    ONE_FINGER_TAP,
    ONE_FINGER_DOUBLE_TAP,
    ONE_FINGER_LONG_PRESS,

    // 2 Fingers
    TWO_FINGER_SWIPE_UP,
    TWO_FINGER_SWIPE_DOWN,
    TWO_FINGER_SWIPE_LEFT,
    TWO_FINGER_SWIPE_RIGHT,
    TWO_FINGER_TAP,

    // 3 Fingers
    THREE_FINGER_SWIPE_UP,
    THREE_FINGER_SWIPE_DOWN,
    THREE_FINGER_SWIPE_LEFT,
    THREE_FINGER_SWIPE_RIGHT,

    // 4 Fingers
    FOUR_FINGER_SWIPE_UP,
    FOUR_FINGER_SWIPE_DOWN,
    FOUR_FINGER_SWIPE_LEFT,
    FOUR_FINGER_SWIPE_RIGHT,

    UNKNOWN
}
